In [2]:
import numpy as np

### Задание 1

Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [3]:
a = np.arange(12, 24)
print(a)


[12 13 14 15 16 17 18 19 20 21 22 23]


### Задание 2

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [15]:
a1 = a.reshape(2, 6)
a2 = a.reshape(3, 4)
a3 = a.reshape(6, 2)
a4 = a.reshape(4, 3)
a5 = a.reshape(12, 1)
print(f"Первый двухмерный массив и его размерность, равняется: {a1.ndim}:\n {a1} ")
print(f"Второй двухмерный массив и его размерность, равняется: {a2.ndim}:\n {a2}")
print(f"Третий двухмерный массив и его размерность, равняется: {a3.ndim}:\n {a3}")
print(f"Четвертый двухмерный массив и его размерность, равняется: {a4.ndim}:\n {a4}")
print(f"Пятый двухмерный массив и его размерность, равняется: {a5.ndim}:\n {a5}")

Первый двухмерный массив и его размерность, равняется: 2:
 [[12 13 14 15 16 17]
 [18 19 20 21 22 23]] 
Второй двухмерный массив и его размерность, равняется: 2:
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Третий двухмерный массив и его размерность, равняется: 2:
 [[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
Четвертый двухмерный массив и его размерность, равняется: 2:
 [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
Пятый двухмерный массив и его размерность, равняется: 2:
 [[12 13 14 15 16 17 18 19 20 21 22 23]]


### Задание 3

Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1
(в трех примерах - для обозначения числа столбцов, в двух - для строк).


In [16]:
a1=a.reshape(2, -1)
a2=a.reshape(3, -1)
a3=a.reshape(-1, 2)
a4=a.reshape(-1, 3)
a5=a.reshape(12, -1)
print(f"Первый двухмерный массив и его размерность, равняется: {a1.ndim}:\n {a1} ")
print(f"Второй двухмерный массив и его размерность, равняется: {a2.ndim}:\n {a2}")
print(f"Третий двухмерный массив и его размерность, равняется: {a3.ndim}:\n {a3}")
print(f"Четвертый двухмерный массив и его размерность, равняется: {a4.ndim}:\n {a4}")
print(f"Пятый двухмерный массив и его размерность, равняется: {a5.ndim}:\n {a5}")

Первый двухмерный массив и его размерность, равняется: 2:
 [[12 13 14 15 16 17]
 [18 19 20 21 22 23]] 
Второй двухмерный массив и его размерность, равняется: 2:
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Третий двухмерный массив и его размерность, равняется: 2:
 [[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
Четвертый двухмерный массив и его размерность, равняется: 2:
 [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
Пятый двухмерный массив и его размерность, равняется: 2:
 [[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


### Задание 4

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [29]:
print("Чтобы ответить на этот вопрос, сравним два массива: x и y. Массив будет изначально создан, как одномерный. "
      "Массив 'y' будет создан как reshape от двумерного")
x=np.arange(12, 24)
matrix=x.reshape(3,4)
y=matrix.reshape(12,1)

print(f"Массив 'x' и его размерность, равняется: {x.ndim} и его форма {x.shape}:\n {x} ")
print(f"Массив 'y' и его размерность, равняется: {y.ndim} и его форма {y.shape}:\n {y} ")

print("Из примера четко видно, что одномерный массив и массив Numpy, состоящий из одного столбца и 12 строк, "
      "различаются. Последний, в отличии от первого, \n имеет номер строки и номер столбца, выводится как двумерный "
      "массив с дополнительными []. Таким образом, массив Numpy, состоящий из одного столбца \nи 12 строк, "
      "НЕЛЬЗЯ назвать одномерным.")

Чтобы ответить на этот вопрос, сравним два массива: x и y. Массив будет изначально создан, как одномерный. Массив 'y' будет создан как reshape от двумерного
Массив 'x' и его размерность, равняется: 1 и его форма (12,):
 [12 13 14 15 16 17 18 19 20 21 22 23] 
Массив 'y' и его размерность, равняется: 2 и его форма (12, 1):
 [[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]] 
Из примера четко видно, что одномерный массив и массив Numpy, состоящий из одного столбца и 12 строк, различаются. Последний, в отличии от первого, 
 имеет номер строки и номер столбца, выводится как двумерный массив с дополнительными []. Таким образом, массив Numpy, состоящий из одного столбца 
и 12 строк, НЕЛЬЗЯ назвать одномерным.


### Задание 5

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения
со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким
же атрибутом size, как и исходный массив.

In [38]:
massive_float = np.random.randn (3, 4)
print(f"Размерность массива, составляет - {massive_float.ndim} "
      f"и его размер - {massive_float.size}: \n {massive_float}")

massive_one = massive_float.flatten()
print(f"Размерность массива, составляет - {massive_one.ndim} "
      f"и его размер - {massive_one.size}: \n {massive_one}")

Размерность массива, составляет - 2 и его размер - 12: 
 [[ 1.22952897 -1.16047344 -0.91204012 -1.33439532]
 [ 0.67121048 -0.86088906 -0.93045337 -0.05580375]
 [-0.15592397 -0.18864581  0.1382841   0.80624987]]
Размерность массива, составляет - 1 и его размер - 12: 
 [ 1.22952897 -1.16047344 -0.91204012 -1.33439532  0.67121048 -0.86088906
 -0.93045337 -0.05580375 -0.15592397 -0.18864581  0.1382841   0.80624987]


### Задание 6

Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [47]:
a = np.arange(20, 0, -2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


### Задание 7

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2.
В чем разница между массивами a и b?

In [53]:
b = np.arange(20, 1, -2).reshape(1, 10)
print(b)

print(f"Размерность массива 'a', составляет - {a.ndim},\nа размерность массива 'b', составляет - {b.ndim}.")
print("Вот и ответ, массив 'a' - является одномерным массивом, в массив 'b' - является двухмерным.")


[[20 18 16 14 12 10  8  6  4  2]]
Размерность массива 'a', составляет - 1,
а размерность массива 'b', составляет - 2


### Задание 8

Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше,
чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [84]:
a = np.zeros((2, 2))
print(f"Массив 'a':\n{a}")
b = np.ones((3, 2))
print(f"Массив 'b':\n{b}")
c = np.vstack((a, b))
print(f"Размер итогова массива, составляет - {c.size}, \nмассив 'c': \n{c}")

Массив 'a':
[[0. 0.]
 [0. 0.]]
Массив 'b':
[[1. 1.]
 [1. 1.]
 [1. 1.]]
Размер итогова массива, составляет - 10, 
массив 'c': 
[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


### Задание 9

Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива,
чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем
транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.
Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [100]:
a = np.arange(0, 12)
print(a)
A = a.reshape(4, 3)
print(A)
At = A.transpose()
print(At)
B = np.matmul(A, At)
print(B)
print(f"Матрица 'B', имеет размер - {b.shape}")
print(f"Вычислить обратную матрицу для матрицы 'B' не получится, т.к. это вырожденная (сингулярная) матрица")

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
Матрица 'B', имеет размер - (3, 2)


LinAlgError: Singular matrix

### Задание 10

Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.


In [106]:
np.random.seed(42)

### Задание 11

Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых
чисел от 0 до 16 невключительно.

In [109]:
c = np.random.randint(0, 16, 16)
print(c)

[11  9  5 12 11  8  0 10 10 14  9 15 11 11 15 14]


### Задание 12

Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B
из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [125]:
C = c.reshape(4, -1)
print(f"Матрица 'C':\n{C}")
D = B + C * 10
print(f"Матрица 'D':\n{D}")
print(f"Определитель матрицы 'D', сооставляет - {np.linalg.det(D)}")
print(f"Ранг матрицы 'D', сооставляет - {np.linalg.matrix_rank(D)}")
D_inv = np.linalg.inv(D)
print(f"Обратная матрица 'D':\n{D_inv}")

Матрица 'C':
[[11  9  5 12]
 [11  8  0 10]
 [10 14  9 15]
 [11 11 15 14]]
Матрица 'D':
[[115 104  73 152]
 [124 130  86 222]
 [123 226 239 362]
 [142 232 362 442]]
Определитель матрицы 'D', сооставляет - 62650800.0
Ранг матрицы 'D', сооставляет - 4
Обратная матрица 'D':
[[ 0.01886552 -0.00325327 -0.01147599  0.00454519]
 [ 0.01683203 -0.02439777  0.02559361 -0.01449559]
 [ 0.01273886 -0.01565599 -0.00270994  0.00570208]
 [-0.02532897  0.02667356 -0.00752744  0.00374073]]


### Задание 13

Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv
остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы
B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий
элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых
соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.


In [126]:
D_inv = np.where(D_inv < 0, 0,1)
print(D_inv)
E = np.where(D_inv == 1, B, C)
print(f"Матрица 'E':\n{E}")

[[1 0 0 1]
 [1 0 1 0]
 [1 0 0 1]
 [0 1 0 1]]
Матрица 'E':
[[  5   9   5  32]
 [ 14   8  86  10]
 [ 23  14   9 212]
 [ 11 122  15 302]]
